---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: ^patches/
      - id: end-of-file-fixer
        exclude: ^patches/
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/errata-ai/vale
    rev: v2.23.0
    hooks:
      - id: vale

  - repo: https://github.com/jlebar/pre-commit-hooks.git
    rev: fb5e481f35f5a9b32a06ccfc28b8d6dda4525f75
    hooks:
      - id: bazel-buildifier
        name: buildifier format
      - id: bazel-buildifier
        name: buildifier lint
        args:
          - -lint=warn

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
      - id: clang-format
        exclude: ^(docs/|^llvm-project-overlay/)

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
      - id: pymarkdown
        exclude: ^(docs/reference/|docs/rules/)
        args:
          - --config=.pymarkdown.json
          - scan

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint

    # TODO: Use the official repo when this patch is merged.
  - repo: https://github.com/taoufik07/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args:
          - --color=always
